name: bip
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1 # update with constant.dart

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  dynamic_color: ^1.7.0
  flutter_localizations:
    sdk: flutter
  intl: any
  rxdart: ^0.28.0
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  html: ^0.15.5
  shared_preferences: ^2.3.3
  crypto: ^3.0.6
  path_provider: ^2.1.5
  flutter_svg: ^2.0.16
  shelf: ^1.4.1
  drift: ^2.21.0
  drift_flutter: ^0.2.4
  barcode_widget: ^2.0.4
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.3.2
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.11
  test: ^1.25.15
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.5.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/img/

