// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/collections_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bip/domain/interfaces/collection_manager.dart' as _i2;
import 'package:bip/domain/model/media_collection.dart' as _i4;
import 'package:bip/domain/model/media_page_preview.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CollectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCollectionManager extends _i1.Mock implements _i2.CollectionManager {
  @override
  _i3.Stream<List<_i4.MediaCollection>> requestMediaCollections(
          {String? sourceName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaCollections,
          [],
          {#sourceName: sourceName},
        ),
        returnValue: _i3.Stream<List<_i4.MediaCollection>>.empty(),
        returnValueForMissingStub:
            _i3.Stream<List<_i4.MediaCollection>>.empty(),
      ) as _i3.Stream<List<_i4.MediaCollection>>);

  @override
  _i3.Future<bool> saveMediaCollection(_i4.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMediaCollection,
          [collection],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteMediaCollection(_i4.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMediaCollection,
          [collection],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> addToMediaCollection(
    _i4.MediaCollection? collection,
    _i5.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeFromMediaCollection(
    _i4.MediaCollection? collection,
    _i5.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isInMediaCollection(_i5.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #isInMediaCollection,
          [preview],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeFromAllMediaCollection(
          _i5.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromAllMediaCollection,
          [preview],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i5.MediaPagePreview>> requestMediaCollectionDetail(
    _i4.MediaCollection? collection, {
    String? key = '',
    int? pageNumber = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaCollectionDetail,
          [collection],
          {
            #key: key,
            #pageNumber: pageNumber,
          },
        ),
        returnValue: _i3.Future<List<_i5.MediaPagePreview>>.value(
            <_i5.MediaPagePreview>[]),
        returnValueForMissingStub: _i3.Future<List<_i5.MediaPagePreview>>.value(
            <_i5.MediaPagePreview>[]),
      ) as _i3.Future<List<_i5.MediaPagePreview>>);
}
