// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/main_bangumi_sub_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:bip/domain/interfaces/media_manager.dart' as _i5;
import 'package:bip/domain/interfaces/source.dart' as _i3;
import 'package:bip/domain/model/index_configuration.dart' as _i4;
import 'package:bip/domain/model/media_info.dart' as _i10;
import 'package:bip/domain/model/media_page_detail.dart' as _i9;
import 'package:bip/domain/model/media_page_preview.dart' as _i6;
import 'package:bip/domain/model/reply.dart' as _i12;
import 'package:bip/domain/model/user_info.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBehaviorSubject_0<T> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T> {
  _FakeBehaviorSubject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSourceApiResult_1<T> extends _i1.SmartFake
    implements _i3.SourceApiResult<T> {
  _FakeSourceApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIndexConfiguration_2 extends _i1.SmartFake
    implements _i4.IndexConfiguration {
  _FakeIndexConfiguration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MediaManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaManager extends _i1.Mock implements _i5.MediaManager {
  @override
  _i2.BehaviorSubject<List<_i6.MediaPagePreview>> get homeExploreList =>
      (super.noSuchMethod(
        Invocation.getter(#homeExploreList),
        returnValue: _FakeBehaviorSubject_0<List<_i6.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<List<_i6.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
      ) as _i2.BehaviorSubject<List<_i6.MediaPagePreview>>);

  @override
  _i2.BehaviorSubject<Map<String, _i7.UserInfo?>> get accounts =>
      (super.noSuchMethod(
        Invocation.getter(#accounts),
        returnValue: _FakeBehaviorSubject_0<Map<String, _i7.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<Map<String, _i7.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
      ) as _i2.BehaviorSubject<Map<String, _i7.UserInfo?>>);

  @override
  _i8.Future<void> explore() => (super.noSuchMethod(
        Invocation.method(
          #explore,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> refreshExplore() => (super.noSuchMethod(
        Invocation.method(
          #refreshExplore,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Stream<List<_i6.MediaPagePreview>> requestSearch(
    String? keyword,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearch,
          [
            keyword,
            pageNumber,
          ],
        ),
        returnValue: _i8.Stream<List<_i6.MediaPagePreview>>.empty(),
        returnValueForMissingStub:
            _i8.Stream<List<_i6.MediaPagePreview>>.empty(),
      ) as _i8.Stream<List<_i6.MediaPagePreview>>);

  @override
  _i8.Future<_i3.SourceApiResult<List<String>>> requestSearchHot() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearchHot,
          [],
        ),
        returnValue: _i8.Future<_i3.SourceApiResult<List<String>>>.value(
            _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.SourceApiResult<List<String>>>.value(
                _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
      ) as _i8.Future<_i3.SourceApiResult<List<String>>>);

  @override
  _i8.Future<_i4.IndexConfiguration> requestBangumiIndexConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndexConfiguration,
          [],
        ),
        returnValue:
            _i8.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
      ) as _i8.Future<_i4.IndexConfiguration>);

  @override
  _i8.Future<
      _i3.SourceApiResult<List<_i6.MediaPagePreview>>> requestBangumiIndex(
    _i4.IndexConfiguration? configuration,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndex,
          [
            configuration,
            pageNumber,
          ],
        ),
        returnValue:
            _i8.Future<_i3.SourceApiResult<List<_i6.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i6.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.SourceApiResult<List<_i6.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i6.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i3.SourceApiResult<List<_i6.MediaPagePreview>>>);

  @override
  _i8.Future<_i3.SourceApiResult<_i9.MediaPageDetail>> requestDetail(
          _i6.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDetail,
          [preview],
        ),
        returnValue: _i8.Future<_i3.SourceApiResult<_i9.MediaPageDetail>>.value(
            _FakeSourceApiResult_1<_i9.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.SourceApiResult<_i9.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i9.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
      ) as _i8.Future<_i3.SourceApiResult<_i9.MediaPageDetail>>);

  @override
  _i8.Future<_i3.SourceApiResult<_i10.MediaInfo>> requestMediaInfo(
          _i10.MediaInfo? mediaInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaInfo,
          [mediaInfo],
        ),
        returnValue: _i8.Future<_i3.SourceApiResult<_i10.MediaInfo>>.value(
            _FakeSourceApiResult_1<_i10.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.SourceApiResult<_i10.MediaInfo>>.value(
                _FakeSourceApiResult_1<_i10.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
      ) as _i8.Future<_i3.SourceApiResult<_i10.MediaInfo>>);

  @override
  _i8.Future<String> requestLoginQr(String? sourceName) => (super.noSuchMethod(
        Invocation.method(
          #requestLoginQr,
          [sourceName],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i3.SourceLoginResult> validateLoginQr(String? sourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateLoginQr,
          [sourceName],
        ),
        returnValue: _i8.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
        returnValueForMissingStub: _i8.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
      ) as _i8.Future<_i3.SourceLoginResult>);

  @override
  _i8.Future<_i3.SourceApiResult<List<_i12.Reply>>> requestReplies(
    _i9.MediaPageDetail? page,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestReplies,
          [
            page,
            pageNumber,
          ],
        ),
        returnValue: _i8.Future<_i3.SourceApiResult<List<_i12.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i12.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.SourceApiResult<List<_i12.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i12.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i3.SourceApiResult<List<_i12.Reply>>>);

  @override
  _i8.Future<_i3.SourceApiResult<List<_i12.Reply>>> requestSubReplies(
    _i12.Reply? reply,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSubReplies,
          [
            reply,
            pageNumber,
          ],
        ),
        returnValue: _i8.Future<_i3.SourceApiResult<List<_i12.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i12.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.SourceApiResult<List<_i12.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i12.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i3.SourceApiResult<List<_i12.Reply>>>);
}
