// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/main_mine_sub_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i17;

import 'package:bip/domain/interfaces/media_manager.dart' as _i7;
import 'package:bip/domain/interfaces/source.dart' as _i3;
import 'package:bip/domain/model/index_configuration.dart' as _i4;
import 'package:bip/domain/model/media_info.dart' as _i12;
import 'package:bip/domain/model/media_page_detail.dart' as _i11;
import 'package:bip/domain/model/media_page_preview.dart' as _i8;
import 'package:bip/domain/model/reply.dart' as _i14;
import 'package:bip/domain/model/user_info.dart' as _i9;
import 'package:bip/utils/bip_router.dart' as _i15;
import 'package:bip/utils/page_info.dart' as _i16;
import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBehaviorSubject_0<T> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T> {
  _FakeBehaviorSubject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSourceApiResult_1<T> extends _i1.SmartFake
    implements _i3.SourceApiResult<T> {
  _FakeSourceApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIndexConfiguration_2 extends _i1.SmartFake
    implements _i4.IndexConfiguration {
  _FakeIndexConfiguration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_3<T extends _i5.State<_i5.StatefulWidget>>
    extends _i1.SmartFake implements _i5.GlobalKey<T> {
  _FakeGlobalKey_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_4 extends _i1.SmartFake implements _i5.Widget {
  _FakeWidget_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakePage_5<T> extends _i1.SmartFake implements _i5.Page<T> {
  _FakePage_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MediaManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaManager extends _i1.Mock implements _i7.MediaManager {
  @override
  _i2.BehaviorSubject<List<_i8.MediaPagePreview>> get homeExploreList =>
      (super.noSuchMethod(
        Invocation.getter(#homeExploreList),
        returnValue: _FakeBehaviorSubject_0<List<_i8.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<List<_i8.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
      ) as _i2.BehaviorSubject<List<_i8.MediaPagePreview>>);

  @override
  _i2.BehaviorSubject<Map<String, _i9.UserInfo?>> get accounts =>
      (super.noSuchMethod(
        Invocation.getter(#accounts),
        returnValue: _FakeBehaviorSubject_0<Map<String, _i9.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<Map<String, _i9.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
      ) as _i2.BehaviorSubject<Map<String, _i9.UserInfo?>>);

  @override
  _i10.Future<void> explore() => (super.noSuchMethod(
        Invocation.method(
          #explore,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> refreshExplore() => (super.noSuchMethod(
        Invocation.method(
          #refreshExplore,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Stream<List<_i8.MediaPagePreview>> requestSearch(
    String? keyword,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearch,
          [
            keyword,
            pageNumber,
          ],
        ),
        returnValue: _i10.Stream<List<_i8.MediaPagePreview>>.empty(),
        returnValueForMissingStub:
            _i10.Stream<List<_i8.MediaPagePreview>>.empty(),
      ) as _i10.Stream<List<_i8.MediaPagePreview>>);

  @override
  _i10.Future<_i3.SourceApiResult<List<String>>> requestSearchHot() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearchHot,
          [],
        ),
        returnValue: _i10.Future<_i3.SourceApiResult<List<String>>>.value(
            _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i3.SourceApiResult<List<String>>>.value(
                _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
      ) as _i10.Future<_i3.SourceApiResult<List<String>>>);

  @override
  _i10.Future<_i4.IndexConfiguration> requestBangumiIndexConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndexConfiguration,
          [],
        ),
        returnValue:
            _i10.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
      ) as _i10.Future<_i4.IndexConfiguration>);

  @override
  _i10.Future<
      _i3.SourceApiResult<List<_i8.MediaPagePreview>>> requestBangumiIndex(
    _i4.IndexConfiguration? configuration,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndex,
          [
            configuration,
            pageNumber,
          ],
        ),
        returnValue:
            _i10.Future<_i3.SourceApiResult<List<_i8.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i8.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i3.SourceApiResult<List<_i8.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i8.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
      ) as _i10.Future<_i3.SourceApiResult<List<_i8.MediaPagePreview>>>);

  @override
  _i10.Future<_i3.SourceApiResult<_i11.MediaPageDetail>> requestDetail(
          _i8.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDetail,
          [preview],
        ),
        returnValue:
            _i10.Future<_i3.SourceApiResult<_i11.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i11.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i3.SourceApiResult<_i11.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i11.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
      ) as _i10.Future<_i3.SourceApiResult<_i11.MediaPageDetail>>);

  @override
  _i10.Future<_i3.SourceApiResult<_i12.MediaInfo>> requestMediaInfo(
          _i12.MediaInfo? mediaInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaInfo,
          [mediaInfo],
        ),
        returnValue: _i10.Future<_i3.SourceApiResult<_i12.MediaInfo>>.value(
            _FakeSourceApiResult_1<_i12.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i3.SourceApiResult<_i12.MediaInfo>>.value(
                _FakeSourceApiResult_1<_i12.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
      ) as _i10.Future<_i3.SourceApiResult<_i12.MediaInfo>>);

  @override
  _i10.Future<String> requestLoginQr(String? sourceName) => (super.noSuchMethod(
        Invocation.method(
          #requestLoginQr,
          [sourceName],
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i3.SourceLoginResult> validateLoginQr(String? sourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateLoginQr,
          [sourceName],
        ),
        returnValue: _i10.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
        returnValueForMissingStub: _i10.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
      ) as _i10.Future<_i3.SourceLoginResult>);

  @override
  _i10.Future<_i3.SourceApiResult<List<_i14.Reply>>> requestReplies(
    _i11.MediaPageDetail? page,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestReplies,
          [
            page,
            pageNumber,
          ],
        ),
        returnValue: _i10.Future<_i3.SourceApiResult<List<_i14.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i14.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i3.SourceApiResult<List<_i14.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i14.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
      ) as _i10.Future<_i3.SourceApiResult<List<_i14.Reply>>>);

  @override
  _i10.Future<_i3.SourceApiResult<List<_i14.Reply>>> requestSubReplies(
    _i14.Reply? reply,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSubReplies,
          [
            reply,
            pageNumber,
          ],
        ),
        returnValue: _i10.Future<_i3.SourceApiResult<List<_i14.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i14.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i3.SourceApiResult<List<_i14.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i14.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
      ) as _i10.Future<_i3.SourceApiResult<List<_i14.Reply>>>);
}

/// A class which mocks [BipRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockBipRouter extends _i1.Mock implements _i15.BipRouter {
  @override
  _i5.GlobalKey<_i5.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_3<_i5.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
        returnValueForMissingStub: _FakeGlobalKey_3<_i5.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i5.GlobalKey<_i5.NavigatorState>);

  @override
  List<_i16.PageInfo> get stack => (super.noSuchMethod(
        Invocation.getter(#stack),
        returnValue: <_i16.PageInfo>[],
        returnValueForMissingStub: <_i16.PageInfo>[],
      ) as List<_i16.PageInfo>);

  @override
  set navigatorKey(_i5.GlobalKey<_i5.NavigatorState>? _navigatorKey) =>
      super.noSuchMethod(
        Invocation.setter(
          #navigatorKey,
          _navigatorKey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<void> setNewRoutePath(String? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNewRoutePath,
          [configuration],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i5.Widget build(_i5.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #build,
          [context],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #build,
            [context],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #build,
            [context],
          ),
        ),
      ) as _i5.Widget);

  @override
  bool pop<T extends Object?>([T? result]) => (super.noSuchMethod(
        Invocation.method(
          #pop,
          [result],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<bool> maybePop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
        Invocation.method(
          #maybePop,
          [result],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i5.Page<dynamic> createPage(_i16.PageInfo? page) => (super.noSuchMethod(
        Invocation.method(
          #createPage,
          [page],
        ),
        returnValue: _FakePage_5<dynamic>(
          this,
          Invocation.method(
            #createPage,
            [page],
          ),
        ),
        returnValueForMissingStub: _FakePage_5<dynamic>(
          this,
          Invocation.method(
            #createPage,
            [page],
          ),
        ),
      ) as _i5.Page<dynamic>);

  @override
  _i10.Future<dynamic> push(String? newRoute) => (super.noSuchMethod(
        Invocation.method(
          #push,
          [newRoute],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> pushPageInfo(_i16.PageInfo? pageInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushPageInfo,
          [pageInfo],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<void> setInitialRoutePath(String? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInitialRoutePath,
          [configuration],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setRestoredRoutePath(String? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRestoredRoutePath,
          [configuration],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> popRoute() => (super.noSuchMethod(
        Invocation.method(
          #popRoute,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
