// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/media_page_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i15;

import 'package:bip/domain/interfaces/bip_player.dart' as _i14;
import 'package:bip/domain/interfaces/collection_manager.dart' as _i20;
import 'package:bip/domain/interfaces/database.dart' as _i16;
import 'package:bip/domain/interfaces/media_manager.dart' as _i6;
import 'package:bip/domain/interfaces/source.dart' as _i3;
import 'package:bip/domain/model/index_configuration.dart' as _i4;
import 'package:bip/domain/model/media_collection.dart' as _i19;
import 'package:bip/domain/model/media_info.dart' as _i11;
import 'package:bip/domain/model/media_page_detail.dart' as _i10;
import 'package:bip/domain/model/media_page_history.dart' as _i18;
import 'package:bip/domain/model/media_page_preview.dart' as _i7;
import 'package:bip/domain/model/reply.dart' as _i13;
import 'package:bip/domain/model/search_history.dart' as _i17;
import 'package:bip/domain/model/user_info.dart' as _i8;
import 'package:media_kit/media_kit.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBehaviorSubject_0<T> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T> {
  _FakeBehaviorSubject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSourceApiResult_1<T> extends _i1.SmartFake
    implements _i3.SourceApiResult<T> {
  _FakeSourceApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIndexConfiguration_2 extends _i1.SmartFake
    implements _i4.IndexConfiguration {
  _FakeIndexConfiguration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerState_3 extends _i1.SmartFake implements _i5.PlayerState {
  _FakePlayerState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerStream_4 extends _i1.SmartFake implements _i5.PlayerStream {
  _FakePlayerStream_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MediaManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaManager extends _i1.Mock implements _i6.MediaManager {
  @override
  _i2.BehaviorSubject<List<_i7.MediaPagePreview>> get homeExploreList =>
      (super.noSuchMethod(
        Invocation.getter(#homeExploreList),
        returnValue: _FakeBehaviorSubject_0<List<_i7.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<List<_i7.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
      ) as _i2.BehaviorSubject<List<_i7.MediaPagePreview>>);

  @override
  _i2.BehaviorSubject<Map<String, _i8.UserInfo?>> get accounts =>
      (super.noSuchMethod(
        Invocation.getter(#accounts),
        returnValue: _FakeBehaviorSubject_0<Map<String, _i8.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<Map<String, _i8.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
      ) as _i2.BehaviorSubject<Map<String, _i8.UserInfo?>>);

  @override
  _i9.Future<void> explore() => (super.noSuchMethod(
        Invocation.method(
          #explore,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> refreshExplore() => (super.noSuchMethod(
        Invocation.method(
          #refreshExplore,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<List<_i7.MediaPagePreview>> requestSearch(
    String? keyword,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearch,
          [
            keyword,
            pageNumber,
          ],
        ),
        returnValue: _i9.Stream<List<_i7.MediaPagePreview>>.empty(),
        returnValueForMissingStub:
            _i9.Stream<List<_i7.MediaPagePreview>>.empty(),
      ) as _i9.Stream<List<_i7.MediaPagePreview>>);

  @override
  _i9.Future<_i3.SourceApiResult<List<String>>> requestSearchHot() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearchHot,
          [],
        ),
        returnValue: _i9.Future<_i3.SourceApiResult<List<String>>>.value(
            _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.SourceApiResult<List<String>>>.value(
                _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
      ) as _i9.Future<_i3.SourceApiResult<List<String>>>);

  @override
  _i9.Future<_i4.IndexConfiguration> requestBangumiIndexConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndexConfiguration,
          [],
        ),
        returnValue:
            _i9.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
      ) as _i9.Future<_i4.IndexConfiguration>);

  @override
  _i9.Future<
      _i3.SourceApiResult<List<_i7.MediaPagePreview>>> requestBangumiIndex(
    _i4.IndexConfiguration? configuration,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndex,
          [
            configuration,
            pageNumber,
          ],
        ),
        returnValue:
            _i9.Future<_i3.SourceApiResult<List<_i7.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i7.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.SourceApiResult<List<_i7.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i7.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
      ) as _i9.Future<_i3.SourceApiResult<List<_i7.MediaPagePreview>>>);

  @override
  _i9.Future<_i3.SourceApiResult<_i10.MediaPageDetail>> requestDetail(
          _i7.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDetail,
          [preview],
        ),
        returnValue:
            _i9.Future<_i3.SourceApiResult<_i10.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i10.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.SourceApiResult<_i10.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i10.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
      ) as _i9.Future<_i3.SourceApiResult<_i10.MediaPageDetail>>);

  @override
  _i9.Future<_i3.SourceApiResult<_i11.MediaInfo>> requestMediaInfo(
          _i11.MediaInfo? mediaInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaInfo,
          [mediaInfo],
        ),
        returnValue: _i9.Future<_i3.SourceApiResult<_i11.MediaInfo>>.value(
            _FakeSourceApiResult_1<_i11.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.SourceApiResult<_i11.MediaInfo>>.value(
                _FakeSourceApiResult_1<_i11.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
      ) as _i9.Future<_i3.SourceApiResult<_i11.MediaInfo>>);

  @override
  _i9.Future<String> requestLoginQr(String? sourceName) => (super.noSuchMethod(
        Invocation.method(
          #requestLoginQr,
          [sourceName],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i3.SourceLoginResult> validateLoginQr(String? sourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateLoginQr,
          [sourceName],
        ),
        returnValue: _i9.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
        returnValueForMissingStub: _i9.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
      ) as _i9.Future<_i3.SourceLoginResult>);

  @override
  _i9.Future<_i3.SourceApiResult<List<_i13.Reply>>> requestReplies(
    _i10.MediaPageDetail? page,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestReplies,
          [
            page,
            pageNumber,
          ],
        ),
        returnValue: _i9.Future<_i3.SourceApiResult<List<_i13.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i13.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.SourceApiResult<List<_i13.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i13.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
      ) as _i9.Future<_i3.SourceApiResult<List<_i13.Reply>>>);

  @override
  _i9.Future<_i3.SourceApiResult<List<_i13.Reply>>> requestSubReplies(
    _i13.Reply? reply,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSubReplies,
          [
            reply,
            pageNumber,
          ],
        ),
        returnValue: _i9.Future<_i3.SourceApiResult<List<_i13.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i13.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.SourceApiResult<List<_i13.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i13.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
      ) as _i9.Future<_i3.SourceApiResult<List<_i13.Reply>>>);
}

/// A class which mocks [BipPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockBipPlayer extends _i1.Mock implements _i14.BipPlayer {
  @override
  _i5.PlayerState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePlayerState_3(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakePlayerState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.PlayerState);

  @override
  _i5.PlayerStream get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _FakePlayerStream_4(
          this,
          Invocation.getter(#stream),
        ),
        returnValueForMissingStub: _FakePlayerStream_4(
          this,
          Invocation.getter(#stream),
        ),
      ) as _i5.PlayerStream);

  @override
  _i5.PlayerStream get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _FakePlayerStream_4(
          this,
          Invocation.getter(#streams),
        ),
        returnValueForMissingStub: _FakePlayerStream_4(
          this,
          Invocation.getter(#streams),
        ),
      ) as _i5.PlayerStream);

  @override
  _i9.Future<int> get handle => (super.noSuchMethod(
        Invocation.getter(#handle),
        returnValue: _i9.Future<int>.value(0),
        returnValueForMissingStub: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  set platform(_i5.PlatformPlayer? _platform) => super.noSuchMethod(
        Invocation.setter(
          #platform,
          _platform,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> open(
    _i5.Playable? playable, {
    bool? play = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [playable],
          {#play: play},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> playOrPause() => (super.noSuchMethod(
        Invocation.method(
          #playOrPause,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> add(_i5.Media? media) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [media],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> remove(int? index) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [index],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> next() => (super.noSuchMethod(
        Invocation.method(
          #next,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> previous() => (super.noSuchMethod(
        Invocation.method(
          #previous,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> jump(int? index) => (super.noSuchMethod(
        Invocation.method(
          #jump,
          [index],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> move(
    int? from,
    int? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #move,
          [
            from,
            to,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> seek(Duration? duration) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [duration],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setPlaylistMode(_i5.PlaylistMode? playlistMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPlaylistMode,
          [playlistMode],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setRate(double? rate) => (super.noSuchMethod(
        Invocation.method(
          #setRate,
          [rate],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setPitch(double? pitch) => (super.noSuchMethod(
        Invocation.method(
          #setPitch,
          [pitch],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setShuffle(bool? shuffle) => (super.noSuchMethod(
        Invocation.method(
          #setShuffle,
          [shuffle],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setAudioDevice(_i5.AudioDevice? audioDevice) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioDevice,
          [audioDevice],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setVideoTrack(_i5.VideoTrack? track) => (super.noSuchMethod(
        Invocation.method(
          #setVideoTrack,
          [track],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setAudioTrack(_i5.AudioTrack? track) => (super.noSuchMethod(
        Invocation.method(
          #setAudioTrack,
          [track],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setSubtitleTrack(_i5.SubtitleTrack? track) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubtitleTrack,
          [track],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i15.Uint8List?> screenshot({String? format = 'image/jpeg'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #screenshot,
          [],
          {#format: format},
        ),
        returnValue: _i9.Future<_i15.Uint8List?>.value(),
        returnValueForMissingStub: _i9.Future<_i15.Uint8List?>.value(),
      ) as _i9.Future<_i15.Uint8List?>);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i16.Database {
  @override
  _i9.Stream<List<_i17.SearchHistory>> get searchHistoryStream =>
      (super.noSuchMethod(
        Invocation.getter(#searchHistoryStream),
        returnValue: _i9.Stream<List<_i17.SearchHistory>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i17.SearchHistory>>.empty(),
      ) as _i9.Stream<List<_i17.SearchHistory>>);

  @override
  _i9.Future<void> saveSearchHistory(_i17.SearchHistory? history) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSearchHistory,
          [history],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> clearSearchHistories() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistories,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i18.MediaPageHistory>> queryMediaPageHistory({
    String? key = '',
    int? pageNumber = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMediaPageHistory,
          [],
          {
            #key: key,
            #pageNumber: pageNumber,
          },
        ),
        returnValue: _i9.Future<List<_i18.MediaPageHistory>>.value(
            <_i18.MediaPageHistory>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i18.MediaPageHistory>>.value(
                <_i18.MediaPageHistory>[]),
      ) as _i9.Future<List<_i18.MediaPageHistory>>);

  @override
  _i9.Future<void> saveMediaPageHistory(_i18.MediaPageHistory? history) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMediaPageHistory,
          [history],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i19.MediaCollection>> queryMediaCollections() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMediaCollections,
          [],
        ),
        returnValue: _i9.Future<List<_i19.MediaCollection>>.value(
            <_i19.MediaCollection>[]),
        returnValueForMissingStub: _i9.Future<List<_i19.MediaCollection>>.value(
            <_i19.MediaCollection>[]),
      ) as _i9.Future<List<_i19.MediaCollection>>);

  @override
  _i9.Future<bool> saveMediaCollection(_i19.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMediaCollection,
          [collection],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> deleteMediaCollection(_i19.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMediaCollection,
          [collection],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> addToMediaCollection(
    _i19.MediaCollection? collection,
    _i7.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> removeFromMediaCollection(
    _i19.MediaCollection? collection,
    _i7.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> isInMediaCollection(_i7.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #isInMediaCollection,
          [preview],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<List<_i7.MediaPagePreview>> queryMediaCollectionDetail(
    _i19.MediaCollection? collection, {
    String? key = '',
    int? pageNumber = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMediaCollectionDetail,
          [collection],
          {
            #key: key,
            #pageNumber: pageNumber,
          },
        ),
        returnValue: _i9.Future<List<_i7.MediaPagePreview>>.value(
            <_i7.MediaPagePreview>[]),
        returnValueForMissingStub: _i9.Future<List<_i7.MediaPagePreview>>.value(
            <_i7.MediaPagePreview>[]),
      ) as _i9.Future<List<_i7.MediaPagePreview>>);
}

/// A class which mocks [CollectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCollectionManager extends _i1.Mock implements _i20.CollectionManager {
  @override
  _i9.Stream<List<_i19.MediaCollection>> requestMediaCollections(
          {String? sourceName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaCollections,
          [],
          {#sourceName: sourceName},
        ),
        returnValue: _i9.Stream<List<_i19.MediaCollection>>.empty(),
        returnValueForMissingStub:
            _i9.Stream<List<_i19.MediaCollection>>.empty(),
      ) as _i9.Stream<List<_i19.MediaCollection>>);

  @override
  _i9.Future<bool> saveMediaCollection(_i19.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMediaCollection,
          [collection],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> deleteMediaCollection(_i19.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMediaCollection,
          [collection],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> addToMediaCollection(
    _i19.MediaCollection? collection,
    _i7.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> removeFromMediaCollection(
    _i19.MediaCollection? collection,
    _i7.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> isInMediaCollection(_i7.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #isInMediaCollection,
          [preview],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> removeFromAllMediaCollection(
          _i7.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromAllMediaCollection,
          [preview],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<List<_i7.MediaPagePreview>> requestMediaCollectionDetail(
    _i19.MediaCollection? collection, {
    String? key = '',
    int? pageNumber = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaCollectionDetail,
          [collection],
          {
            #key: key,
            #pageNumber: pageNumber,
          },
        ),
        returnValue: _i9.Future<List<_i7.MediaPagePreview>>.value(
            <_i7.MediaPagePreview>[]),
        returnValueForMissingStub: _i9.Future<List<_i7.MediaPagePreview>>.value(
            <_i7.MediaPagePreview>[]),
      ) as _i9.Future<List<_i7.MediaPagePreview>>);
}
