// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/reply_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i5;

import 'package:bip/domain/interfaces/media_manager.dart' as _i8;
import 'package:bip/domain/interfaces/source.dart' as _i3;
import 'package:bip/domain/model/index_configuration.dart' as _i4;
import 'package:bip/domain/model/media_info.dart' as _i13;
import 'package:bip/domain/model/media_page_detail.dart' as _i12;
import 'package:bip/domain/model/media_page_preview.dart' as _i9;
import 'package:bip/domain/model/reply.dart' as _i15;
import 'package:bip/domain/model/user_info.dart' as _i10;
import 'package:flutter/foundation.dart' as _i7;
import 'package:flutter/src/widgets/focus_manager.dart' as _i6;
import 'package:flutter/src/widgets/focus_traversal.dart' as _i17;
import 'package:flutter/src/widgets/framework.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBehaviorSubject_0<T> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T> {
  _FakeBehaviorSubject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSourceApiResult_1<T> extends _i1.SmartFake
    implements _i3.SourceApiResult<T> {
  _FakeSourceApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIndexConfiguration_2 extends _i1.SmartFake
    implements _i4.IndexConfiguration {
  _FakeIndexConfiguration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSize_3 extends _i1.SmartFake implements _i5.Size {
  _FakeSize_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffset_4 extends _i1.SmartFake implements _i5.Offset {
  _FakeOffset_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_5 extends _i1.SmartFake implements _i5.Rect {
  _FakeRect_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFocusAttachment_6 extends _i1.SmartFake
    implements _i6.FocusAttachment {
  _FakeFocusAttachment_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDiagnosticsNode_7 extends _i1.SmartFake
    implements _i7.DiagnosticsNode {
  _FakeDiagnosticsNode_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i7.TextTreeConfiguration? parentConfiguration,
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [MediaManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaManager extends _i1.Mock implements _i8.MediaManager {
  @override
  _i2.BehaviorSubject<List<_i9.MediaPagePreview>> get homeExploreList =>
      (super.noSuchMethod(
        Invocation.getter(#homeExploreList),
        returnValue: _FakeBehaviorSubject_0<List<_i9.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<List<_i9.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
      ) as _i2.BehaviorSubject<List<_i9.MediaPagePreview>>);

  @override
  _i2.BehaviorSubject<Map<String, _i10.UserInfo?>> get accounts =>
      (super.noSuchMethod(
        Invocation.getter(#accounts),
        returnValue: _FakeBehaviorSubject_0<Map<String, _i10.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<Map<String, _i10.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
      ) as _i2.BehaviorSubject<Map<String, _i10.UserInfo?>>);

  @override
  _i11.Future<void> explore() => (super.noSuchMethod(
        Invocation.method(
          #explore,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> refreshExplore() => (super.noSuchMethod(
        Invocation.method(
          #refreshExplore,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Stream<List<_i9.MediaPagePreview>> requestSearch(
    String? keyword,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearch,
          [
            keyword,
            pageNumber,
          ],
        ),
        returnValue: _i11.Stream<List<_i9.MediaPagePreview>>.empty(),
        returnValueForMissingStub:
            _i11.Stream<List<_i9.MediaPagePreview>>.empty(),
      ) as _i11.Stream<List<_i9.MediaPagePreview>>);

  @override
  _i11.Future<_i3.SourceApiResult<List<String>>> requestSearchHot() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearchHot,
          [],
        ),
        returnValue: _i11.Future<_i3.SourceApiResult<List<String>>>.value(
            _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SourceApiResult<List<String>>>.value(
                _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
      ) as _i11.Future<_i3.SourceApiResult<List<String>>>);

  @override
  _i11.Future<_i4.IndexConfiguration> requestBangumiIndexConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndexConfiguration,
          [],
        ),
        returnValue:
            _i11.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
      ) as _i11.Future<_i4.IndexConfiguration>);

  @override
  _i11.Future<
      _i3.SourceApiResult<List<_i9.MediaPagePreview>>> requestBangumiIndex(
    _i4.IndexConfiguration? configuration,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndex,
          [
            configuration,
            pageNumber,
          ],
        ),
        returnValue:
            _i11.Future<_i3.SourceApiResult<List<_i9.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i9.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SourceApiResult<List<_i9.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i9.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
      ) as _i11.Future<_i3.SourceApiResult<List<_i9.MediaPagePreview>>>);

  @override
  _i11.Future<_i3.SourceApiResult<_i12.MediaPageDetail>> requestDetail(
          _i9.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDetail,
          [preview],
        ),
        returnValue:
            _i11.Future<_i3.SourceApiResult<_i12.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i12.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SourceApiResult<_i12.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i12.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
      ) as _i11.Future<_i3.SourceApiResult<_i12.MediaPageDetail>>);

  @override
  _i11.Future<_i3.SourceApiResult<_i13.MediaInfo>> requestMediaInfo(
          _i13.MediaInfo? mediaInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaInfo,
          [mediaInfo],
        ),
        returnValue: _i11.Future<_i3.SourceApiResult<_i13.MediaInfo>>.value(
            _FakeSourceApiResult_1<_i13.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SourceApiResult<_i13.MediaInfo>>.value(
                _FakeSourceApiResult_1<_i13.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
      ) as _i11.Future<_i3.SourceApiResult<_i13.MediaInfo>>);

  @override
  _i11.Future<String> requestLoginQr(String? sourceName) => (super.noSuchMethod(
        Invocation.method(
          #requestLoginQr,
          [sourceName],
        ),
        returnValue: _i11.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i3.SourceLoginResult> validateLoginQr(String? sourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateLoginQr,
          [sourceName],
        ),
        returnValue: _i11.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
        returnValueForMissingStub: _i11.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
      ) as _i11.Future<_i3.SourceLoginResult>);

  @override
  _i11.Future<_i3.SourceApiResult<List<_i15.Reply>>> requestReplies(
    _i12.MediaPageDetail? page,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestReplies,
          [
            page,
            pageNumber,
          ],
        ),
        returnValue: _i11.Future<_i3.SourceApiResult<List<_i15.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i15.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SourceApiResult<List<_i15.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i15.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
      ) as _i11.Future<_i3.SourceApiResult<List<_i15.Reply>>>);

  @override
  _i11.Future<_i3.SourceApiResult<List<_i15.Reply>>> requestSubReplies(
    _i15.Reply? reply,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSubReplies,
          [
            reply,
            pageNumber,
          ],
        ),
        returnValue: _i11.Future<_i3.SourceApiResult<List<_i15.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i15.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SourceApiResult<List<_i15.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i15.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
      ) as _i11.Future<_i3.SourceApiResult<List<_i15.Reply>>>);
}

/// A class which mocks [FocusNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockFocusNode extends _i1.Mock implements _i6.FocusNode {
  @override
  bool get skipTraversal => (super.noSuchMethod(
        Invocation.getter(#skipTraversal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canRequestFocus => (super.noSuchMethod(
        Invocation.getter(#canRequestFocus),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get descendantsAreFocusable => (super.noSuchMethod(
        Invocation.getter(#descendantsAreFocusable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get descendantsAreTraversable => (super.noSuchMethod(
        Invocation.getter(#descendantsAreTraversable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Iterable<_i6.FocusNode> get children => (super.noSuchMethod(
        Invocation.getter(#children),
        returnValue: <_i6.FocusNode>[],
        returnValueForMissingStub: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  Iterable<_i6.FocusNode> get traversalChildren => (super.noSuchMethod(
        Invocation.getter(#traversalChildren),
        returnValue: <_i6.FocusNode>[],
        returnValueForMissingStub: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  Iterable<_i6.FocusNode> get descendants => (super.noSuchMethod(
        Invocation.getter(#descendants),
        returnValue: <_i6.FocusNode>[],
        returnValueForMissingStub: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  Iterable<_i6.FocusNode> get traversalDescendants => (super.noSuchMethod(
        Invocation.getter(#traversalDescendants),
        returnValue: <_i6.FocusNode>[],
        returnValueForMissingStub: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  Iterable<_i6.FocusNode> get ancestors => (super.noSuchMethod(
        Invocation.getter(#ancestors),
        returnValue: <_i6.FocusNode>[],
        returnValueForMissingStub: <_i6.FocusNode>[],
      ) as Iterable<_i6.FocusNode>);

  @override
  bool get hasFocus => (super.noSuchMethod(
        Invocation.getter(#hasFocus),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasPrimaryFocus => (super.noSuchMethod(
        Invocation.getter(#hasPrimaryFocus),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.FocusHighlightMode get highlightMode => (super.noSuchMethod(
        Invocation.getter(#highlightMode),
        returnValue: _i6.FocusHighlightMode.touch,
        returnValueForMissingStub: _i6.FocusHighlightMode.touch,
      ) as _i6.FocusHighlightMode);

  @override
  _i5.Size get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeSize_3(
          this,
          Invocation.getter(#size),
        ),
        returnValueForMissingStub: _FakeSize_3(
          this,
          Invocation.getter(#size),
        ),
      ) as _i5.Size);

  @override
  _i5.Offset get offset => (super.noSuchMethod(
        Invocation.getter(#offset),
        returnValue: _FakeOffset_4(
          this,
          Invocation.getter(#offset),
        ),
        returnValueForMissingStub: _FakeOffset_4(
          this,
          Invocation.getter(#offset),
        ),
      ) as _i5.Offset);

  @override
  _i5.Rect get rect => (super.noSuchMethod(
        Invocation.getter(#rect),
        returnValue: _FakeRect_5(
          this,
          Invocation.getter(#rect),
        ),
        returnValueForMissingStub: _FakeRect_5(
          this,
          Invocation.getter(#rect),
        ),
      ) as _i5.Rect);

  @override
  set onKey(_i6.FocusOnKeyCallback? _onKey) => super.noSuchMethod(
        Invocation.setter(
          #onKey,
          _onKey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onKeyEvent(_i6.FocusOnKeyEventCallback? _onKeyEvent) =>
      super.noSuchMethod(
        Invocation.setter(
          #onKeyEvent,
          _onKeyEvent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set skipTraversal(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #skipTraversal,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set canRequestFocus(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #canRequestFocus,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set descendantsAreFocusable(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #descendantsAreFocusable,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set descendantsAreTraversable(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #descendantsAreTraversable,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set debugLabel(String? value) => super.noSuchMethod(
        Invocation.setter(
          #debugLabel,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void unfocus(
          {_i6.UnfocusDisposition? disposition =
              _i6.UnfocusDisposition.scope}) =>
      super.noSuchMethod(
        Invocation.method(
          #unfocus,
          [],
          {#disposition: disposition},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool consumeKeyboardToken() => (super.noSuchMethod(
        Invocation.method(
          #consumeKeyboardToken,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.FocusAttachment attach(
    _i16.BuildContext? context, {
    _i6.FocusOnKeyEventCallback? onKeyEvent,
    _i6.FocusOnKeyCallback? onKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #attach,
          [context],
          {
            #onKeyEvent: onKeyEvent,
            #onKey: onKey,
          },
        ),
        returnValue: _FakeFocusAttachment_6(
          this,
          Invocation.method(
            #attach,
            [context],
            {
              #onKeyEvent: onKeyEvent,
              #onKey: onKey,
            },
          ),
        ),
        returnValueForMissingStub: _FakeFocusAttachment_6(
          this,
          Invocation.method(
            #attach,
            [context],
            {
              #onKeyEvent: onKeyEvent,
              #onKey: onKey,
            },
          ),
        ),
      ) as _i6.FocusAttachment);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void requestFocus([_i6.FocusNode? node]) => super.noSuchMethod(
        Invocation.method(
          #requestFocus,
          [node],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool nextFocus() => (super.noSuchMethod(
        Invocation.method(
          #nextFocus,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool previousFocus() => (super.noSuchMethod(
        Invocation.method(
          #previousFocus,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool focusInDirection(_i17.TraversalDirection? direction) =>
      (super.noSuchMethod(
        Invocation.method(
          #focusInDirection,
          [direction],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void debugFillProperties(_i7.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i7.DiagnosticsNode> debugDescribeChildren() => (super.noSuchMethod(
        Invocation.method(
          #debugDescribeChildren,
          [],
        ),
        returnValue: <_i7.DiagnosticsNode>[],
        returnValueForMissingStub: <_i7.DiagnosticsNode>[],
      ) as List<_i7.DiagnosticsNode>);

  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
      ) as String);

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();

  @override
  String toStringShallow({
    String? joiner = ', ',
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringShallow,
          [],
          {
            #joiner: joiner,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  String toStringDeep({
    String? prefixLineOne = '',
    String? prefixOtherLines,
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.debug,
    int? wrapWidth = 65,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringDeep,
          [],
          {
            #prefixLineOne: prefixLineOne,
            #prefixOtherLines: prefixOtherLines,
            #minLevel: minLevel,
            #wrapWidth: wrapWidth,
          },
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
              #wrapWidth: wrapWidth,
            },
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
              #wrapWidth: wrapWidth,
            },
          ),
        ),
      ) as String);

  @override
  _i7.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i7.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i7.DiagnosticsNode);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
