// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bip/domain/interfaces/database.dart' as _i5;
import 'package:bip/domain/interfaces/media_manager.dart' as _i11;
import 'package:bip/domain/interfaces/source.dart' as _i3;
import 'package:bip/domain/model/index_configuration.dart' as _i4;
import 'package:bip/domain/model/media_collection.dart' as _i9;
import 'package:bip/domain/model/media_info.dart' as _i14;
import 'package:bip/domain/model/media_page_detail.dart' as _i13;
import 'package:bip/domain/model/media_page_history.dart' as _i8;
import 'package:bip/domain/model/media_page_preview.dart' as _i10;
import 'package:bip/domain/model/reply.dart' as _i16;
import 'package:bip/domain/model/search_history.dart' as _i7;
import 'package:bip/domain/model/user_info.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBehaviorSubject_0<T> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T> {
  _FakeBehaviorSubject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSourceApiResult_1<T> extends _i1.SmartFake
    implements _i3.SourceApiResult<T> {
  _FakeSourceApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIndexConfiguration_2 extends _i1.SmartFake
    implements _i4.IndexConfiguration {
  _FakeIndexConfiguration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i5.Database {
  @override
  _i6.Stream<List<_i7.SearchHistory>> get searchHistoryStream =>
      (super.noSuchMethod(
        Invocation.getter(#searchHistoryStream),
        returnValue: _i6.Stream<List<_i7.SearchHistory>>.empty(),
        returnValueForMissingStub: _i6.Stream<List<_i7.SearchHistory>>.empty(),
      ) as _i6.Stream<List<_i7.SearchHistory>>);

  @override
  _i6.Future<void> saveSearchHistory(_i7.SearchHistory? history) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSearchHistory,
          [history],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearSearchHistories() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistories,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.MediaPageHistory>> queryMediaPageHistory({
    String? key = '',
    int? pageNumber = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMediaPageHistory,
          [],
          {
            #key: key,
            #pageNumber: pageNumber,
          },
        ),
        returnValue: _i6.Future<List<_i8.MediaPageHistory>>.value(
            <_i8.MediaPageHistory>[]),
        returnValueForMissingStub: _i6.Future<List<_i8.MediaPageHistory>>.value(
            <_i8.MediaPageHistory>[]),
      ) as _i6.Future<List<_i8.MediaPageHistory>>);

  @override
  _i6.Future<void> saveMediaPageHistory(_i8.MediaPageHistory? history) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMediaPageHistory,
          [history],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.MediaCollection>> queryMediaCollections() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMediaCollections,
          [],
        ),
        returnValue: _i6.Future<List<_i9.MediaCollection>>.value(
            <_i9.MediaCollection>[]),
        returnValueForMissingStub: _i6.Future<List<_i9.MediaCollection>>.value(
            <_i9.MediaCollection>[]),
      ) as _i6.Future<List<_i9.MediaCollection>>);

  @override
  _i6.Future<bool> saveMediaCollection(_i9.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMediaCollection,
          [collection],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteMediaCollection(_i9.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMediaCollection,
          [collection],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> addToMediaCollection(
    _i9.MediaCollection? collection,
    _i10.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> removeFromMediaCollection(
    _i9.MediaCollection? collection,
    _i10.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> isInMediaCollection(_i10.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #isInMediaCollection,
          [preview],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i10.MediaPagePreview>> queryMediaCollectionDetail(
    _i9.MediaCollection? collection, {
    String? key = '',
    int? pageNumber = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMediaCollectionDetail,
          [collection],
          {
            #key: key,
            #pageNumber: pageNumber,
          },
        ),
        returnValue: _i6.Future<List<_i10.MediaPagePreview>>.value(
            <_i10.MediaPagePreview>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i10.MediaPagePreview>>.value(
                <_i10.MediaPagePreview>[]),
      ) as _i6.Future<List<_i10.MediaPagePreview>>);
}

/// A class which mocks [MediaManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaManager extends _i1.Mock implements _i11.MediaManager {
  @override
  _i2.BehaviorSubject<List<_i10.MediaPagePreview>> get homeExploreList =>
      (super.noSuchMethod(
        Invocation.getter(#homeExploreList),
        returnValue: _FakeBehaviorSubject_0<List<_i10.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<List<_i10.MediaPagePreview>>(
          this,
          Invocation.getter(#homeExploreList),
        ),
      ) as _i2.BehaviorSubject<List<_i10.MediaPagePreview>>);

  @override
  _i2.BehaviorSubject<Map<String, _i12.UserInfo?>> get accounts =>
      (super.noSuchMethod(
        Invocation.getter(#accounts),
        returnValue: _FakeBehaviorSubject_0<Map<String, _i12.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_0<Map<String, _i12.UserInfo?>>(
          this,
          Invocation.getter(#accounts),
        ),
      ) as _i2.BehaviorSubject<Map<String, _i12.UserInfo?>>);

  @override
  _i6.Future<void> explore() => (super.noSuchMethod(
        Invocation.method(
          #explore,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refreshExplore() => (super.noSuchMethod(
        Invocation.method(
          #refreshExplore,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i10.MediaPagePreview>> requestSearch(
    String? keyword,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearch,
          [
            keyword,
            pageNumber,
          ],
        ),
        returnValue: _i6.Stream<List<_i10.MediaPagePreview>>.empty(),
        returnValueForMissingStub:
            _i6.Stream<List<_i10.MediaPagePreview>>.empty(),
      ) as _i6.Stream<List<_i10.MediaPagePreview>>);

  @override
  _i6.Future<_i3.SourceApiResult<List<String>>> requestSearchHot() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearchHot,
          [],
        ),
        returnValue: _i6.Future<_i3.SourceApiResult<List<String>>>.value(
            _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.SourceApiResult<List<String>>>.value(
                _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
      ) as _i6.Future<_i3.SourceApiResult<List<String>>>);

  @override
  _i6.Future<_i4.IndexConfiguration> requestBangumiIndexConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndexConfiguration,
          [],
        ),
        returnValue:
            _i6.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
      ) as _i6.Future<_i4.IndexConfiguration>);

  @override
  _i6.Future<
      _i3.SourceApiResult<List<_i10.MediaPagePreview>>> requestBangumiIndex(
    _i4.IndexConfiguration? configuration,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndex,
          [
            configuration,
            pageNumber,
          ],
        ),
        returnValue:
            _i6.Future<_i3.SourceApiResult<List<_i10.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i10.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.SourceApiResult<List<_i10.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i10.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
      ) as _i6.Future<_i3.SourceApiResult<List<_i10.MediaPagePreview>>>);

  @override
  _i6.Future<_i3.SourceApiResult<_i13.MediaPageDetail>> requestDetail(
          _i10.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDetail,
          [preview],
        ),
        returnValue:
            _i6.Future<_i3.SourceApiResult<_i13.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i13.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.SourceApiResult<_i13.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i13.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
      ) as _i6.Future<_i3.SourceApiResult<_i13.MediaPageDetail>>);

  @override
  _i6.Future<_i3.SourceApiResult<_i14.MediaInfo>> requestMediaInfo(
          _i14.MediaInfo? mediaInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaInfo,
          [mediaInfo],
        ),
        returnValue: _i6.Future<_i3.SourceApiResult<_i14.MediaInfo>>.value(
            _FakeSourceApiResult_1<_i14.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.SourceApiResult<_i14.MediaInfo>>.value(
                _FakeSourceApiResult_1<_i14.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
      ) as _i6.Future<_i3.SourceApiResult<_i14.MediaInfo>>);

  @override
  _i6.Future<String> requestLoginQr(String? sourceName) => (super.noSuchMethod(
        Invocation.method(
          #requestLoginQr,
          [sourceName],
        ),
        returnValue: _i6.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [sourceName],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i3.SourceLoginResult> validateLoginQr(String? sourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateLoginQr,
          [sourceName],
        ),
        returnValue: _i6.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
        returnValueForMissingStub: _i6.Future<_i3.SourceLoginResult>.value(
            _i3.SourceLoginResult.success),
      ) as _i6.Future<_i3.SourceLoginResult>);

  @override
  _i6.Future<_i3.SourceApiResult<List<_i16.Reply>>> requestReplies(
    _i13.MediaPageDetail? page,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestReplies,
          [
            page,
            pageNumber,
          ],
        ),
        returnValue: _i6.Future<_i3.SourceApiResult<List<_i16.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i16.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.SourceApiResult<List<_i16.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i16.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
      ) as _i6.Future<_i3.SourceApiResult<List<_i16.Reply>>>);

  @override
  _i6.Future<_i3.SourceApiResult<List<_i16.Reply>>> requestSubReplies(
    _i16.Reply? reply,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSubReplies,
          [
            reply,
            pageNumber,
          ],
        ),
        returnValue: _i6.Future<_i3.SourceApiResult<List<_i16.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i16.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.SourceApiResult<List<_i16.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i16.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              reply,
              pageNumber,
            ],
          ),
        )),
      ) as _i6.Future<_i3.SourceApiResult<List<_i16.Reply>>>);
}
