// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/settings_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bip/domain/interfaces/settings_manager.dart' as _i2;
import 'package:bip/domain/model/setting_item.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SettingsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsManager extends _i1.Mock implements _i2.SettingsManager {
  @override
  T getValue<T>(_i3.AppSetting? setting) => (super.noSuchMethod(
        Invocation.method(
          #getValue,
          [setting],
        ),
        returnValue: _i4.dummyValue<T>(
          this,
          Invocation.method(
            #getValue,
            [setting],
          ),
        ),
        returnValueForMissingStub: _i4.dummyValue<T>(
          this,
          Invocation.method(
            #getValue,
            [setting],
          ),
        ),
      ) as T);

  @override
  _i5.Future<void> setValue<T>(
    _i3.AppSetting? setting,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setValue,
          [
            setting,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
