// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/theme_settings_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i2;

import 'package:bip/ui/theme/theme_notifier.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeColor_0 extends _i1.SmartFake implements _i2.Color {
  _FakeColor_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ThemeNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeNotifier extends _i1.Mock implements _i3.ThemeNotifier {
  @override
  bool get isDynamicTheme => (super.noSuchMethod(
        Invocation.getter(#isDynamicTheme),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Color get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _FakeColor_0(
          this,
          Invocation.getter(#value),
        ),
        returnValueForMissingStub: _FakeColor_0(
          this,
          Invocation.getter(#value),
        ),
      ) as _i2.Color);

  @override
  set value(_i2.Color? newValue) => super.noSuchMethod(
        Invocation.setter(
          #value,
          newValue,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setDynamicColor(_i2.Color? color) => super.noSuchMethod(
        Invocation.method(
          #setDynamicColor,
          [color],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Color getDynamicColor() => (super.noSuchMethod(
        Invocation.method(
          #getDynamicColor,
          [],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #getDynamicColor,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeColor_0(
          this,
          Invocation.method(
            #getDynamicColor,
            [],
          ),
        ),
      ) as _i2.Color);

  @override
  bool isPresetColor(_i2.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #isPresetColor,
          [color],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> setThemeColor(
    _i2.Color? color, {
    bool? dynamic = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setThemeColor,
          [color],
          {#dynamic: dynamic},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setDynamicTheme(bool? enable) => (super.noSuchMethod(
        Invocation.method(
          #setDynamicTheme,
          [enable],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
