// Mocks generated by Mockito 5.4.6 from annotations
// in bip/test/bloc/user_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bip/domain/interfaces/source.dart' as _i2;
import 'package:bip/domain/interfaces/source_manager.dart' as _i4;
import 'package:bip/domain/model/index_configuration.dart' as _i3;
import 'package:bip/domain/model/media_collection.dart' as _i13;
import 'package:bip/domain/model/media_info.dart' as _i10;
import 'package:bip/domain/model/media_page_detail.dart' as _i9;
import 'package:bip/domain/model/media_page_preview.dart' as _i7;
import 'package:bip/domain/model/media_type.dart' as _i8;
import 'package:bip/domain/model/reply.dart' as _i11;
import 'package:bip/utils/constant.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSource_0 extends _i1.SmartFake implements _i2.Source {
  _FakeSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSourceApiResult_1<T> extends _i1.SmartFake
    implements _i2.SourceApiResult<T> {
  _FakeSourceApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIndexConfiguration_2 extends _i1.SmartFake
    implements _i3.IndexConfiguration {
  _FakeIndexConfiguration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SourceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSourceManager extends _i1.Mock implements _i4.SourceManager {
  @override
  _i2.Source get mainSource => (super.noSuchMethod(
        Invocation.getter(#mainSource),
        returnValue: _FakeSource_0(
          this,
          Invocation.getter(#mainSource),
        ),
        returnValueForMissingStub: _FakeSource_0(
          this,
          Invocation.getter(#mainSource),
        ),
      ) as _i2.Source);

  @override
  Map<String, _i2.Source> get activeSources => (super.noSuchMethod(
        Invocation.getter(#activeSources),
        returnValue: <String, _i2.Source>{},
        returnValueForMissingStub: <String, _i2.Source>{},
      ) as Map<String, _i2.Source>);
}

/// A class which mocks [Source].
///
/// See the documentation for Mockito's code generation for more information.
class MockSource extends _i1.Mock implements _i2.Source {
  @override
  String get sourceName => (super.noSuchMethod(
        Invocation.getter(#sourceName),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#sourceName),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#sourceName),
        ),
      ) as String);

  @override
  bool get hasAccount => (super.noSuchMethod(
        Invocation.getter(#hasAccount),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<List<_i7.MediaPagePreview>> explore(int? pageNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #explore,
          [pageNumber],
        ),
        returnValue: _i6.Future<List<_i7.MediaPagePreview>>.value(
            <_i7.MediaPagePreview>[]),
        returnValueForMissingStub: _i6.Future<List<_i7.MediaPagePreview>>.value(
            <_i7.MediaPagePreview>[]),
      ) as _i6.Future<List<_i7.MediaPagePreview>>);

  @override
  _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>> search(
    String? keyword,
    int? pageNumber, {
    _i8.MediaType? searchType = _i8.MediaType.video,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [
            keyword,
            pageNumber,
          ],
          {#searchType: searchType},
        ),
        returnValue:
            _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i7.MediaPagePreview>>(
          this,
          Invocation.method(
            #search,
            [
              keyword,
              pageNumber,
            ],
            {#searchType: searchType},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i7.MediaPagePreview>>(
          this,
          Invocation.method(
            #search,
            [
              keyword,
              pageNumber,
            ],
            {#searchType: searchType},
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>);

  @override
  _i6.Future<_i2.SourceApiResult<List<String>>> requestSearchHot() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSearchHot,
          [],
        ),
        returnValue: _i6.Future<_i2.SourceApiResult<List<String>>>.value(
            _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<List<String>>>.value(
                _FakeSourceApiResult_1<List<String>>(
          this,
          Invocation.method(
            #requestSearchHot,
            [],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<List<String>>>);

  @override
  _i6.Future<_i2.SourceApiResult<_i9.MediaPageDetail>> requestDetail(
          _i7.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDetail,
          [preview],
        ),
        returnValue: _i6.Future<_i2.SourceApiResult<_i9.MediaPageDetail>>.value(
            _FakeSourceApiResult_1<_i9.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<_i9.MediaPageDetail>>.value(
                _FakeSourceApiResult_1<_i9.MediaPageDetail>(
          this,
          Invocation.method(
            #requestDetail,
            [preview],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<_i9.MediaPageDetail>>);

  @override
  _i6.Future<_i2.SourceApiResult<_i10.MediaInfo>> requestMediaInfo(
          _i10.MediaInfo? mediaInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaInfo,
          [mediaInfo],
        ),
        returnValue: _i6.Future<_i2.SourceApiResult<_i10.MediaInfo>>.value(
            _FakeSourceApiResult_1<_i10.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<_i10.MediaInfo>>.value(
                _FakeSourceApiResult_1<_i10.MediaInfo>(
          this,
          Invocation.method(
            #requestMediaInfo,
            [mediaInfo],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<_i10.MediaInfo>>);

  @override
  _i6.Future<String> requestLoginQr() => (super.noSuchMethod(
        Invocation.method(
          #requestLoginQr,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #requestLoginQr,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i2.SourceLoginResult> validateLoginQr() => (super.noSuchMethod(
        Invocation.method(
          #validateLoginQr,
          [],
        ),
        returnValue: _i6.Future<_i2.SourceLoginResult>.value(
            _i2.SourceLoginResult.success),
        returnValueForMissingStub: _i6.Future<_i2.SourceLoginResult>.value(
            _i2.SourceLoginResult.success),
      ) as _i6.Future<_i2.SourceLoginResult>);

  @override
  _i6.Future<_i2.SourceApiResult<bool>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<_i2.SourceApiResult<bool>>.value(
            _FakeSourceApiResult_1<bool>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.SourceApiResult<bool>>.value(
            _FakeSourceApiResult_1<bool>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<bool>>);

  @override
  _i6.Future<_i2.SourceApiResult<List<_i11.Reply>>> requestReplies(
    _i9.MediaPageDetail? page,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestReplies,
          [
            page,
            pageNumber,
          ],
        ),
        returnValue: _i6.Future<_i2.SourceApiResult<List<_i11.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i11.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<List<_i11.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i11.Reply>>(
          this,
          Invocation.method(
            #requestReplies,
            [
              page,
              pageNumber,
            ],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<List<_i11.Reply>>>);

  @override
  _i6.Future<_i2.SourceApiResult<List<_i11.Reply>>> requestSubReplies(
    _i11.Reply? parentReply,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSubReplies,
          [
            parentReply,
            pageNumber,
          ],
        ),
        returnValue: _i6.Future<_i2.SourceApiResult<List<_i11.Reply>>>.value(
            _FakeSourceApiResult_1<List<_i11.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              parentReply,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<List<_i11.Reply>>>.value(
                _FakeSourceApiResult_1<List<_i11.Reply>>(
          this,
          Invocation.method(
            #requestSubReplies,
            [
              parentReply,
              pageNumber,
            ],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<List<_i11.Reply>>>);

  @override
  _i6.Future<_i2.SourceApiResult<_i11.Reply>> replyAction(
    _i11.Reply? reply,
    _i12.ReplyAction? action,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replyAction,
          [
            reply,
            action,
          ],
        ),
        returnValue: _i6.Future<_i2.SourceApiResult<_i11.Reply>>.value(
            _FakeSourceApiResult_1<_i11.Reply>(
          this,
          Invocation.method(
            #replyAction,
            [
              reply,
              action,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<_i11.Reply>>.value(
                _FakeSourceApiResult_1<_i11.Reply>(
          this,
          Invocation.method(
            #replyAction,
            [
              reply,
              action,
            ],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<_i11.Reply>>);

  @override
  _i6.Future<
      _i2.SourceApiResult<
          List<_i13.MediaCollection>>> requestMediaCollections() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaCollections,
          [],
        ),
        returnValue:
            _i6.Future<_i2.SourceApiResult<List<_i13.MediaCollection>>>.value(
                _FakeSourceApiResult_1<List<_i13.MediaCollection>>(
          this,
          Invocation.method(
            #requestMediaCollections,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<List<_i13.MediaCollection>>>.value(
                _FakeSourceApiResult_1<List<_i13.MediaCollection>>(
          this,
          Invocation.method(
            #requestMediaCollections,
            [],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<List<_i13.MediaCollection>>>);

  @override
  _i6.Future<bool> saveMediaCollection(_i13.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMediaCollection,
          [collection],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteMediaCollection(_i13.MediaCollection? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMediaCollection,
          [collection],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> addToMediaCollection(
    _i13.MediaCollection? collection,
    _i7.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> removeFromMediaCollection(
    _i13.MediaCollection? collection,
    _i7.MediaPagePreview? preview,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromMediaCollection,
          [
            collection,
            preview,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> removeFromAllMediaCollection(
          _i7.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromAllMediaCollection,
          [preview],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> isInMediaCollection(_i7.MediaPagePreview? preview) =>
      (super.noSuchMethod(
        Invocation.method(
          #isInMediaCollection,
          [preview],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<
      _i2.SourceApiResult<
          List<_i7.MediaPagePreview>>> requestMediaCollectionDetail(
    _i13.MediaCollection? collection, {
    String? key = '',
    int? pageNumber = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMediaCollectionDetail,
          [collection],
          {
            #key: key,
            #pageNumber: pageNumber,
          },
        ),
        returnValue:
            _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i7.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestMediaCollectionDetail,
            [collection],
            {
              #key: key,
              #pageNumber: pageNumber,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i7.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestMediaCollectionDetail,
            [collection],
            {
              #key: key,
              #pageNumber: pageNumber,
            },
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>);

  @override
  _i6.Future<_i3.IndexConfiguration> requestBangumiIndexConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndexConfiguration,
          [],
        ),
        returnValue:
            _i6.Future<_i3.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.IndexConfiguration>.value(_FakeIndexConfiguration_2(
          this,
          Invocation.method(
            #requestBangumiIndexConfiguration,
            [],
          ),
        )),
      ) as _i6.Future<_i3.IndexConfiguration>);

  @override
  _i6.Future<
      _i2.SourceApiResult<List<_i7.MediaPagePreview>>> requestBangumiIndex(
    _i3.IndexConfiguration? configuration,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBangumiIndex,
          [
            configuration,
            pageNumber,
          ],
        ),
        returnValue:
            _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i7.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>.value(
                _FakeSourceApiResult_1<List<_i7.MediaPagePreview>>(
          this,
          Invocation.method(
            #requestBangumiIndex,
            [
              configuration,
              pageNumber,
            ],
          ),
        )),
      ) as _i6.Future<_i2.SourceApiResult<List<_i7.MediaPagePreview>>>);
}
