name: Android CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # set up jdk
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # get keystore
      - name: Checkout Android Keystore
        uses: actions/checkout@v3
        with:
          repository: welcomeworld/keystore
          token: ${{ secrets.CI_TOKEN }}
          path: keystore

      # build apk
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # upload artifact
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: upload-apk
          path: ./app/build/outputs/apk/release/app-release.apk

      # get tag name
      - name: get tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      # upload release
      - name: publish release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./app/build/outputs/apk/release/app-release.apk
          tag_name: ${{ steps.vars.outputs.tag }}
          draft: false
          prerelease: false